### ISSUE TITLE
There are a few typos that need to be corrected to improve the professionalism of the project.

### ISSUE THREAD

**Issue by Zakronindustry** [PATILYASHH/electronics-circuit-simulator#8]
# 1
![image](https://github.com/user-attachments/assets/8c5ad841-7072-4606-bc63-27ae07732f9b)

# 2
![image](https://github.com/user-attachments/assets/5abcc9a9-5ac8-48c8-bbd8-fff37c715073)

# 3
![image](https://github.com/user-attachments/assets/6909ff29-e9b9-4955-86ac-ebccf1462f1b)

**Comment by PATILYASHH** [comment]
Ok I will correct it
